FROM mbentley/teamspeak
LABEL org.freenas.interactive="false" \
      org.freenas.version=1 \
      org.freenas.upgradeable="true" \
      org.freenas.expose-ports-at-host="true" \
      org.freenas.autostart="true" \
      org.freenas.port-mappings="9987:9987/udp,30033:30033/tcp,10011:10011/tcp,411144:41144/tcp" \
      org.freenas.volumes="[						                              \
          {								                                    \
              \"name\": \"/data/teamspeak\",					                        \
              \"descr\": \"Configuration files directory\"		                        \
          }\
       ]"   \                                                                          
      
